RTMS/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('client/', include("client.urls")),
    path('admin/', admin.site.urls),
]

client/urls.py
from django.urls import path, include

from . import views

app_name = "client"
urlpatterns = [
    # ex: /client/
    path("", views.index, name="index"),
    # ex: /client/accounts/
    path("accounts/", include("django.contrib.auth.urls")), 
    # ex: /client/453623
    path("<str:tkt_num>/", views.ticket, name="ticket"),
    # ex: /client/453623/1
    path("<str:tkt_num>/<int:task_num>/", views.task, name="task"),
    # ex: /client/453623/1/254
    path("<str:tkt_num>/<int:task_num>/<int:note_id>/", views.note, name="note"),
    # ex: /client/453623/swap/482134
    path("<str:tkt_num1>/swap/<str:tkt_num2>/", views.swap, name="swap"),
]

client/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    userid      = models.CharField("Unique User ID", max_length=20, unique=True)
    user_name   = models.CharField("User Name", max_length=40)
    user_lvl    = models.IntegerField("User Level", default=0)
    user_status = models.CharField("User Status", max_length=10)
    last_login  = models.DateTimeField("Last Login", blank=True, null=True)
    bad_logins  = models.IntegerField("Bad Logins", default=0)
    
    def __str__(self):
        return self.userid
    
class Ticket(models.Model):
    userid        = models.ForeignKey(User, on_delete=models.CASCADE)
    tkt_num       = models.CharField("Ticket Number", max_length=10)
    title         = models.CharField("Ticket Title", max_length=50)
    description   = models.CharField("Ticket Desciption", max_length=255)
    status        = models.CharField("Ticket Status", max_length=10)
    priority      = models.IntegerField("Ticket Priority", default=0)
    precedence    = models.IntegerField("Ticket Prcedence", default=0)
    requestor     = models.CharField("Ticket Requestor", max_length=50)
    plant         = models.CharField("Ticket Plant", max_length=10)
    assigned_to   = models.CharField("Ticket Assigned To", max_length=20)
    create_date   = models.DateTimeField("Ticket Create Date", blank=True, null=True)
    goal_date     = models.DateTimeField("Ticket Goal Date", blank=True, null=True)
    complete_date = models.DateTimeField("Ticket Complete Date", blank=True, null=True)
    branch        = models.CharField("Ticket Branch", max_length=40)
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['userid', 'tkt_num'], name="%(app_label)s_%(class)s_unique")
        ]
    
    def __str__(self):
        return self.tkt_num
    
class Task(models.Model):
    userid        = models.ForeignKey(User, on_delete=models.CASCADE)
    tkt_num       = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    task_num      = models.IntegerField("Task Number", default=0)
    title         = models.CharField("Task Title", max_length=50)
    description   = models.CharField("Task Desciption", max_length=255)
    status        = models.CharField("Task Status", max_length=10)
    priority      = models.IntegerField("Task Priority", default=0)
    precedence    = models.IntegerField("Task Prcedence", default=0)
    requestor     = models.CharField("Task Requestor", max_length=50)
    plant         = models.CharField("Task Plant", max_length=10)
    assigned_to   = models.CharField("Task Assigned To", max_length=20)
    create_date   = models.DateTimeField("Task Create Date", blank=True, null=True)
    goal_date     = models.DateTimeField("Task Goal Date", blank=True, null=True)
    complete_date = models.DateTimeField("Task Complete Date", blank=True, null=True)
    branch        = models.CharField("Task Branch", max_length=40)
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['userid', 'tkt_num', 'task_num'], name="%(app_label)s_%(class)s_unique")
        ]
    
    def __str__(self):
        return self.task_num
    
class Note(models.Model):
    userid   = models.ForeignKey(User, on_delete=models.CASCADE)
    tkt_num  = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    task_num = models.ForeignKey(Task, on_delete=models.CASCADE)
    note     = models.CharField("Note", max_length=255)
    
    def __str__(self):
        return self.note
    

client/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
# from django.template import loader
from .models import User, Ticket, Task, Note
import json

# Create your views here.
def index(request):
    usr = get_object_or_404(User, userid="jristvedt")
    user_tickets = usr.ticket_set.order_by("precedence")
    # template = loader.get_template("client/index.html")
    context = {
        "usr": usr,
        "user_tickets": user_tickets,
    }
    # return HttpResponse(template.render(context,request))
    return render(request, "client/index.html", context)
    
def ticket(request, tkt_num):

    return HttpResponse("You're looking at ticket %s." % tkt_num)
    
def task(request, tkt_num, task_num):
    return HttpResponse("You're looking at ticket %(tkt)s task %(task)d." % 
                        {'tkt': tkt_num, 'task': task_num})

def note(request, tkt_num, task_num, note_id):
    return HttpResponse("You're looking at note %d." % note_id)
    
def swap(request, tkt_num1, tkt_num2):
    usr = get_object_or_404(User, userid="jristvedt")
    tkt1 = usr.ticket_set.get(tkt_num=tkt_num1)
    tkt2 = usr.ticket_set.get(tkt_num=tkt_num2)
    tmp = tkt2.precedence
    tkt2.precedence = tkt1.precedence
    tkt1.precedence = tmp
    tkt1.save()
    tkt2.save()
    response_data = {'success':1}
    return HttpResponse(json.dumps(response_data), content_type="application/json")
    
def login(request):
    print("login")
    return HttpResponse("howdy")

client/templates/client/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'client/style.css' %}">

<h1>Tickets{% if usr %} for {{ usr.userid }} {% endif %}</h1>
{% if user_tickets %}
    <div class="container">
    {% for tkt in user_tickets %}
        <div draggable="true" class="box" precedence={{ tkt.precedence }} tkt_num={{ tkt.tkt_num }}>
            <b>
            <a href="{% url 'client:ticket' tkt.tkt_num %}">
                {{ tkt.tkt_num }}
            </a>
            &emsp;
                {{ tkt.title }}
            </b>
        </div>
    {% endfor %}
    </div>
{% else %}
    <p>No tickets are available.</p>
{% endif %}

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded', (event) => {

  function handleDragStart(e) {
    this.style.opacity = '0.4';
  
    dragSrcEl = this;
  
    e.dataTransfer.effectAllowed = 'move';
    e.dataTransfer.setData('text/html', this.innerHTML);
  }

  function handleDragEnd(e) {
    this.style.opacity = '1';

    items.forEach(function (item) {
      item.classList.remove('over');
    });
  }

  function handleDragOver(e) {
    e.preventDefault();
    return false;
  }

  function handleDragEnter(e) {
    this.classList.add('over');
  }

  function handleDragLeave(e) {
    this.classList.remove('over');
  }
  
  function handleDrop(e) {
    e.stopPropagation();

    if (dragSrcEl !== this) {
    
      // Swap displayed data
      dragSrcEl.innerHTML = this.innerHTML;
      this.innerHTML = e.dataTransfer.getData('text/html');
      
      // Swap attributes too
      tktPrec = this.attributes["precedence"].value;
      tktNum = this.attributes["tkt_num"].value;
      this.setAttribute("precedence", dragSrcEl.attributes["precedence"].value);
      this.setAttribute("tkt_num", dragSrcEl.attributes["tkt_num"].value);
      dragSrcEl.setAttribute("precedence", tktPrec);
      dragSrcEl.setAttribute("tkt_num", tktNum);
      
      // Send back to the db to remember the order
      url = "{% url 'client:swap' 'PLACEHOLDER1' 'PLACEHOLDER2' %}";
      url = url.replace("PLACEHOLDER1", dragSrcEl.attributes["tkt_num"].value);
      url = url.replace("PLACEHOLDER2", this.attributes["tkt_num"].value);
      $.get(url, function (r){console.log(r);})
    }

    return false;
  }

  let items = document.querySelectorAll('.container .box');
  items.forEach(function(item) {
    item.addEventListener('dragstart', handleDragStart);
    item.addEventListener('dragover', handleDragOver);
    item.addEventListener('dragenter', handleDragEnter);
    item.addEventListener('dragleave', handleDragLeave);
    item.addEventListener('dragend', handleDragEnd);
    item.addEventListener('drop', handleDrop);
  });
});

</script>